package com.springbootplayground.customer;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.util.List;

import static java.time.Month.*;

@Configuration
public class CustomerConfig {

    @Bean
    CommandLineRunner autoPopulateCustomer(CustomerRepository repository) {
        return args -> {

            // ID is removed because it will be autogenerated in the Entity
            Customer frank = new Customer(
                    "frank",
                    "frank@gmail.com",
                    LocalDate.of(1992, APRIL, 3)
            );

            Customer milly = new Customer(
                    "milly",
                    "milly@gmail.com",
                    LocalDate.of(1990, JANUARY, 25)
            );

            repository.saveAll(List.of(frank, milly));
        };
    }
}
