package com.springbootplayground.student;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.util.List;

import static java.time.Month.*;

/**
 * This configuration class is for autopopulate DB when created
 */

@Configuration
public class StudentConfig {

    @Bean
    CommandLineRunner commandLineRunner(StudentRepository repository) {
        return args -> {

            // ID is removed because it will be autogenerated in the Entity
            StudentEntity jamal = new StudentEntity(
                    "Jamal",
                    "jamal@gmail.com",
                    LocalDate.of(1999, APRIL, 3),
                    22
            );

            StudentEntity kasim = new StudentEntity(
                    "Kasim",
                    "kasim@gmail.com",
                    LocalDate.of(1995, JUNE, 25),
                    27
            );

            repository.saveAll(List.of(jamal, kasim));
        };
    }

}
