package com.springbootplayground.customer.configuration;

import com.springbootplayground.customer.entity.Customer;
import com.springbootplayground.customer.entity.CustomerCar;
import com.springbootplayground.customer.repository.CustomerCarRepository;
import com.springbootplayground.customer.repository.CustomerRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.util.List;

import static java.time.Month.*;

@Configuration
public class CustomerConfig {

    @Bean
    CommandLineRunner autoPopulateCustomer(CustomerRepository customerRepository, CustomerCarRepository customerCarRepository) {
        return args -> {

            // populate car data
            CustomerCar ford = new CustomerCar(
                    "Ford",
                    "Ranger"
            );

            CustomerCar toyota = new CustomerCar(
                    "Toyota",
                    "Vios"
            );

            customerCarRepository.saveAll(List.of(ford, toyota));

            // ID is removed because it will be autogenerated in the Entity
            Customer frank = new Customer(
                    "frank",
                    "frank@gmail.com",
                    LocalDate.of(1992, APRIL, 3),
                    ford
            );

            Customer milly = new Customer(
                    "milly",
                    "milly@gmail.com",
                    LocalDate.of(1990, JANUARY, 25),
                    toyota
            );

            customerRepository.saveAll(List.of(frank, milly));
        };
    }
}
